# This is an example Conda environment, for local development
name: pyd-cereal
channels:
  - conda-forge
dependencies:
  - python=3.9 # minimum targeted version is currently 3.9
  - pip
  - pip:
      - -e ".[dev,docs,datatests]"
