site_name: pydantic-cereal

repo_name: NowanIlfideme/pydantic-cereal
repo_url: https://github.com/NowanIlfideme/pydantic-cereal/

site_author: Anatoly Makarevich
site_description: "pydantic-cereal: Advanced serialization for Pydantic models"

# NOTE: This allows looking at docs locally
# See https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
site_url: ""
use_directory_urls: false

nav:
  - "Overview": index.md
  - "Examples":
      - "Minimal Example": examples/minimal.ipynb
      - "Pandas Example": examples/pandas.ipynb
  - "API Reference": reference.md

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  # logo: assets/cereal-logo.svg # to add in docs/assets
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

# Plugins: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options: # https://mkdocstrings.github.io/python/usage/#globallocal-options
            heading_level: 2
            show_root_heading: true

            #
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: true
              warn_unknown_params: false # TODO: Remove when Griffe has Pydantic support
            show_object_full_path: true
            show_signature_annotations: true
            show_bases: true
            show_source: true
            annotations_path: "brief"
            unwrap_annotated: false
          selection:
            filters:
              - "^__init__$" # but always include __init__ modules and methods
              - "!^_" # exlude all members starting with _
  - mkdocs-jupyter:
      include_source: true
      execute: true
      allow_errors: false # Enforce up-to-date documentation
      # kernel_name: python3
      # ignore_h1_titles: true

markdown_extensions:
  - admonition
  - pymdownx.details # extra stuff for Admonition
  - pymdownx.emoji
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  # - mkdocs-click
  # - markdown_include.include:
  #     base_path: docs
  # - toc:
  #     permalink: "🔗"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NowanIlfideme/pydantic-cereal/
